#!/usr/bin/env python3
"""
hermes_exporter.py - Bridge: reads 9router DB and generates hermes_* dashboard metrics.
"""
import sqlite3
import os
import tempfile
import math
from datetime import datetime, timezone

DB_PATH = "/root/.9router/db/data.sqlite"
OUTPUT_PATH = "/var/lib/alloy/textfile/hermes.prom"
BUDGET_MONTHLY = 50.0

def sanitize_label(name):
    if name is None:
        return "unknown"
    name = name.replace("/", "_").replace("-", "_").replace(" ", "_")
    return "".join(c for c in name if c.isalnum() or c == "_")

def export():
    conn = sqlite3.connect(DB_PATH)

    # Total counts
    total = conn.execute("""
        SELECT COUNT(*), COALESCE(SUM(promptTokens), 0), COALESCE(SUM(completionTokens), 0),
               COALESCE(SUM(cost), 0)
        FROM usageHistory
    """).fetchone()
    total_requests = total[0] or 0
    total_input = total[1] or 0
    total_output = total[2] or 0
    total_cost = total[3] or 0.0

    # Per model
    models = conn.execute("""
        SELECT model, COUNT(*), COALESCE(SUM(promptTokens), 0),
               COALESCE(SUM(completionTokens), 0), COALESCE(SUM(cost), 0)
        FROM usageHistory GROUP BY model
    """).fetchall()

    # Monthly spend
    month = datetime.now(timezone.utc).strftime("%Y-%m")
    monthly = conn.execute("""
        SELECT COALESCE(SUM(cost), 0) FROM usageHistory
        WHERE strftime('%%Y-%%m', datetime(timestamp/1000, 'unixepoch')) = ?
    """, (month,)).fetchone()[0]

    # Daily spend
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    daily = conn.execute("""
        SELECT COALESCE(SUM(cost), 0) FROM usageHistory
        WHERE strftime('%%Y-%%m-%%d', datetime(timestamp/1000, 'unixepoch')) = ?
    """, (today,)).fetchone()[0]

    conn.close()

    ts = int(datetime.now(timezone.utc).timestamp())

    lines = []
    lines.append("# Hermes dashboard metrics — generated by hermes_exporter.py")
    lines.append("")

    # Spending & Budget
    lines.append("# HELP hermes_cost_total Cumulative spend in USD")
    lines.append("# TYPE hermes_cost_total gauge")
    lines.append(f"hermes_cost_total {total_cost:.6f} {ts}")

    lines.append("# HELP hermes_cost_monthly_budget Monthly budget limit in USD")
    lines.append("# TYPE hermes_cost_monthly_budget gauge")
    lines.append(f"hermes_cost_monthly_budget {BUDGET_MONTHLY} {ts}")

    lines.append("# HELP hermes_cost_budget_remaining Remaining budget in USD")
    lines.append("# TYPE hermes_cost_budget_remaining gauge")
    lines.append(f"hermes_cost_budget_remaining {max(0, BUDGET_MONTHLY - monthly):.6f} {ts}")

    lines.append("# HELP hermes_cost_daily_spend Daily spend in USD")
    lines.append("# TYPE hermes_cost_daily_spend gauge")
    lines.append(f"hermes_cost_daily_spend {daily:.6f} {ts}")

    projected = (monthly / max(1, datetime.now(timezone.utc).day)) * 30
    lines.append("# HELP hermes_cost_projected_monthly Projected monthly spend in USD")
    lines.append("# TYPE hermes_cost_projected_monthly gauge")
    lines.append(f"hermes_cost_projected_monthly {projected:.6f} {ts}")

    budget_pct = (monthly / BUDGET_MONTHLY) * 100
    lines.append("# HELP hermes_cost_budget_percent Budget usage percentage")
    lines.append("# TYPE hermes_cost_budget_percent gauge")
    lines.append(f"hermes_cost_budget_percent {budget_pct:.1f} {ts}")

    zone = 0 if budget_pct < 50 else (1 if budget_pct < 75 else (2 if budget_pct < 90 else 3))
    zone_names = ["green", "yellow", "orange", "red"]
    lines.append("# HELP hermes_budget_zone Budget zone (0=G, 1=Y, 2=O, 3=R)")
    lines.append("# TYPE hermes_budget_zone gauge")
    lines.append(f"hermes_budget_zone {zone} {ts}")

    for i, zn in enumerate(zone_names):
        lines.append(f'hermes_budget_zone_info{{zone="{zn}"}} {"1" if i == zone else "0"} {ts}')

    lines.append("")

    # Model tokens usage
    for m in models:
        model_name, reqs, inp, out, cost = m
        label = sanitize_label(model_name)
        total_tokens = inp + out
        limit = 10000000

        lines.append(f'hermes_model_tokens_used{{model="{label}"}} {total_tokens} {ts}')
        lines.append(f'hermes_model_tokens_limit{{model="{label}"}} {limit} {ts}')
        pct = (total_tokens / limit) * 100 if limit > 0 else 0
        lines.append(f'hermes_model_usage_percent{{model="{label}"}} {pct:.2f} {ts}')

    lines.append("")

    # Quota placeholders
    lines.append("# HELP hermes_quota_limit Quota limit per provider")
    lines.append("# TYPE hermes_quota_limit gauge")
    for m in models:
        label = sanitize_label(m[0])
        lines.append(f'hermes_quota_limit{{provider="{label}",type="rpm"}} 30 {ts}')
        lines.append(f'hermes_quota_limit{{provider="{label}",type="daily"}} 1000 {ts}')
        lines.append(f'hermes_quota_remaining{{provider="{label}",type="rpm"}} 30 {ts}')
        lines.append(f'hermes_quota_remaining{{provider="{label}",type="daily"}} 1000 {ts}')
        lines.append(f'hermes_quota_percent{{provider="{label}",type="rpm"}} 0 {ts}')
        lines.append(f'hermes_quota_percent{{provider="{label}",type="daily"}} 0 {ts}')

    lines.append("")

    # Active alerts (none)
    lines.append("# HELP hermes_active_alerts Active alerts count")
    lines.append("# TYPE hermes_active_alerts gauge")
    lines.append(f'hermes_active_alerts{{severity="warning"}} 0 {ts}')
    lines.append(f'hermes_active_alerts{{severity="critical"}} 0 {ts}')

    content = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(OUTPUT_PATH))
    with os.fdopen(fd, "w") as f:
        f.write(content)
    os.replace(tmp, OUTPUT_PATH)
    print(f"Wrote {OUTPUT_PATH}", file=__import__('sys').stderr)

if __name__ == "__main__":
    export()
